favicon: /images/myfavicon.png
banner: /images/webstack_banner_cn.png

logo:
  expanded: /images/gudie_dark.png
  collapsed: /images/myfavicon2x.png
  dark: /images/gudie_dark.png

# 修改了index.ejs，添加了if判断，取消了flag的显示
flag:
  enable: false
  data:
    - name: 简体中文
      default: true
      icon: flag-cn
      index: /index.html

search: true

userDefinedSearchData:
  custom: true
  thisSearch: https://www.baidu.com/s?wd=
  thisSearchIcon: url(https://www.baidu.com/favicon.ico)
  hotStatus: true
  data:
    - name: phind
      img: url(https://www.phind.com/images/favicon.png)
      url: https://www.phind.com/search?q=
    - name: perplexity
      img: url(/images/logos/perplexity.png)
      url: https://www.perplexity.ai/?q=
    - name: 百度
      img: url(https://www.baidu.com/favicon.ico)
      url: https://www.baidu.com/s?wd=
    - name: bing
      img: url(/images/logos/bing_logo.jpg)
      url: https://cn.bing.com/search?q=
    - name: github
      img: url(/images/logos/github.png)
      url: https://github.com/search?q=
    - name: B站
      img: url(https://www.bilibili.com/favicon.ico?v=1)
      url: https://search.bilibili.com/all?keyword=


#githubCorner: '<a href="https://github.com/HCLonely/hexo-theme-webstack" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

expandAll: true
menu:
  - name: 常用网站
    icon: far fa-star
    config: mainPage
  - name: 问答社区
    icon: fas fa-question
    config: qa
  - name: 好用工具
    icon: fas fa-tools
    config: hotTools
  - name: 图床汇总
    icon: fas fa-file-image
    config: imgTools
  - name: 博客聚合
    icon: fas fa-user-friends
    config: blogPro

mainPage:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 全球最大交友网站
  - name: Gitee
    url: https://gitee.com/
    img: /images/logos/gitee.ico
    description: 面向开源及私有软件项目的托管平台
  - name: Netlify
    url: https://www.netlify.com/
    img: /images/logos/63df6ab81e69f.png
    description: 访问超快的免费的部署平台
  - name: Vercel
    url: https://vercel.com/
    img: https://assets.vercel.com/image/upload/front/favicon/vercel/57x57.png
    description: 免费好用的部署平台
  - name: bilibili
    url: https://www.bilibili.com/
    img: https://www.bilibili.com/favicon.ico?v=1
    description: 鼠鼠我啊...
  - name: leetcode
    url: https://leetcode.cn/
    img: https://static.leetcode.cn/cn-mono-assets/production/assets/favicon-notification-96x96.3211fd5a.png
    description: 刷题刷刷刷
  - name: 牛客网
    url: https://www.nowcoder.com/
    img: https://static.nowcoder.com/images/logo_web_300.png
    description: 刷题刷刷刷
  - name: CSDN
    url: https://blog.csdn.net/
    img: https://g.csdnimg.cn/static/logo/favicon32.ico
    description: 专业开发者社区
  - name: 阿里云
    url: https://www.aliyun.com/
    img: https://img.alicdn.com/tfs/TB1_ZXuNcfpK1RjSZFOXXa6nFXa-32-32.ico
    description: 为了无法计算的价值
  - name: 腾讯云
    url: https://cloud.tencent.com/
    img: https://cloudcache.tencent-cloud.com/open_proj/proj_qcloud_v2/gateway/shareicons/cloud.png
    description: 产业质变·云启未来
  - name: 又拍云
    url: https://www.upyun.com/
    img: https://www.upyun.com/static/favicon-64x64.png
    description: 加入联盟，白嫖CDN
  - name: 知乎
    url: https://www.zhihu.com/
    img: https://static.zhihu.com/heifetz/assets/apple-touch-icon-76.7abf3393.png
    description: 人在蒙古，刚下航母
  
qa:
  - name: stackoverflow
    url: https://stackoverflow.com/
    img: https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png?v=c78bd457575a
    description: 全球热门的编程学习社区
  - name: CSDN问答
    url: https://ask.csdn.net/
    img: https://g.csdnimg.cn/static/logo/favicon32.ico
    description: CSDN开发者互助问答
  - name: 思否
    url: https://segmentfault.com/questions
    img: https://static.segmentfault.com/main_site_next/fab8c45a/touch-icon.png
    description: 以开放、对等、共享的理念，凝聚开发者智慧，共同推动技术进步

hotTools:
  - name: docsmall
    url: https://docsmall.com/gif-compress
    img: https://docsmall.com/favicon.png
    description: 在线图片Gif压缩
  - name: ico51
    url: http://www.ico51.cn/
    img: http://www.ico51.cn/favicon.ico
    description: 在线透明ico制作
  - name: tinyPng
    url: https://tinypng.com/
    img: /images/logos/tinify.png
    description: 在线图片压缩
  - name: 菜鸟教程
    url: https://www.runoob.com/
    img: https://static.runoob.com/images/favicon.ico
    description: 从编程入门到入门编程
  - name: 樱花frp
    url: https://www.natfrp.com/
    img: https://www.natfrp.com/favicon.ico
    description: 易用的内网穿透服务
  - name: 51.la
    url: https://v6.51.la/
    img: /images/logos/51la.ico
    description: 免费的站点监测
  - name: itdog
    url: https://www.itdog.cn/http/
    img: /images/logos/63de41e1a4dae.png
    description: 网站速度诊断
  - name: myssl
    url: https://myssl.com/
    img: /images/logos/63de41cf0f0ed.png
    description: 网站ssl证书测试
  - name: cpolar
    url: https://www.cpolar.com/
    img: https://www.cpolar.com/wp-content/uploads/2016/10/cropped-site-icon-1-1-32x32.png
    description: 快速将服务公开，但带宽和收费感人，不如楼上
  - name: joyssl
    url: https://www.joyssl.com/
    img: https://www.joyssl.com/images/favicon.ico
    description: 白嫖域名ssl证书
  - name: apifox
    url: https://www.apifox.cn/
    img: https://cdn.apifox.cn/logo/apifox-logo-256.png
    description: postman，懂？
  - name: itool
    url: https://itool.co/timestamp
    img: https://itool.co/static/icons/apple-icon-57x57.png
    description: 各类在线工具
  - name: 彩云
    url: https://docs.caiyunapp.com/blog
    img: https://docs.caiyunapp.com/img/favicon.ico
    description: 免费的天气、翻译api
  - name: shields.io
    url: https://shields.io/
    img: /images/logos/63e4b49d38888.png
    description: diy一个badge
  - name: matools
    url: https://www.matools.com/
    img: https://www.matools.com/img/common/favicon.png
    description: 程序猿可用的在线工具
  - name: font-awesome
    url: https://wpmore.cn/resources/font-awesome/
    img: https://wpmore.cn/favicon.ico
    description: 字体图标对照
  - name: 吱吱工具箱
    url: https://www.butterpig.top/
    img: https://s1.ax1x.com/2022/08/01/vAiw8O.png
    description: 在线图片处理工具
  - name: uigradients
    url: https://uigradients.com/#Miaka
    img: https://uigradients.com/static/images/favicon-32x32.png
    description: 好看的渐变色
  - name: cplusplus.com
    url: https://legacy.cplusplus.com/
    img: https://legacy.cplusplus.com/favicon.ico
    description: C/C++文档
  - name: phind
    url: https://www.phind.com/
    img: https://www.phind.com/images/favicon.png
    description: 体验AI搜索引擎 | 停止国内服务
  - name: DoGet
    url: https://doget.nocsdn.com/#/
    img: https://doget.nocsdn.com/icons/favicon-32x32.png
    description: Github下载加速
  - name: word2md
    url: https://word2md.com/
    img: /images/logos/6416affb642cb.png
    description: word文档转换为markdown


imgTools:
  - name: 慕雪的图床 (已下线)
    url: /
    img: /images/myfavicon.png
    description: 自建图床（无需登录）
  - name: 图床导航
    url: http://imgdh.com/#
    img: /images/logos/imgguide.png
    description: 图床聚合收录 (不稳定)
  - name: 路过图床
    url: https://imgse.com/
    img: https://imgse.com/content/images/system/favicon_1587118523486_91617a.png
    description: 免费图床 (无需登录 | 稳定)
  - name: imgtp
    url: https://www.imgtp.com/
    img: /images/logos/imgtp.ico
    description: 免费图床 (无需登录)
  - name: postimages
    url: https://postimages.org/
    img: https://postimages.org/favicon.ico
    description: 免费图床 (无需登录)
  - name: KOOK 图床
    url: https://www.kookapp.cn/
    img: https://www.kookapp.cn/favicon.ico
    description: 你以为这只是个语音软件？
  - name: 图片存储
    url: https://pic.xywm.ltd/
    img: https://p1.xywm.ltd/2023/03/22/358c6f19e90dcba8b4841ae6e61827dd.png
    description: 免费图床 (无需登录 | 稳定)
  - name: imgloc
    url: https://imgloc.com/
    img: https://imgloc.com/content/images/system/favicon_1670917776761_0a194d.png
    description: 免费图床 (无需登录 | 稳定)

blogPro:
  - name: travellings
    url: https://www.travellings.cn/
    img: https://www.travellings.cn/assets/travelling-dark.png
    description: 开往 · 友链接力！
  - name: 十年之约
    url: https://www.foreverblog.cn/
    img: https://www.foreverblog.cn/favicon.ico
    description: 一个人的寂寞，一群人的狂欢。
  - name: 萌国icp备案
    url: https://icp.gov.moe/
    img: https://icp.gov.moe/favicon.ico
    description: 萌ICP备 纯属萌友网站联萌！
  - name: Valorant商店在线查询
    url: https://val.musnow.top/
    img: https://img.musnow.top/i/2023/02/63e1f966cc776.ico
    description: 在线调用api，查询valorant商店
  - name: 酷壳
    url: https://coolshell.cn/
    img: https://coolshell.cn/wp-content/uploads/2020/04/mini.logo_.png
    description: 享受编程和技术带来的乐趣
  - name: 代码随想录
    url: https://www.programmercarl.com/
    img: https://img-blog.csdnimg.cn/20210614201246512.png
    description: 学习算法不迷路
  - name: 果核剥壳
    url: https://www.ghxi.com/
    img: https://www.ghxi.com/favicon.ico
    description: 互联网的净土
  - name: khl.py文档
    url: https://khl-py.eu.org/
    img: https://khl-py.eu.org/favicon.ico
    description: KOOK平台khl.py-SDK文档


about:
  url: /about/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是hexo主题<a href="https://github.com/HCLonely/hexo-theme-webstack">hexo-theme-webstack</a>的导航站点。</p></blockquote><font color="black">
    <h4>免责声明</h4></font></br><p><font color="black" size=3>
    本站对网页中所显示的信息或资料的准确性、内容、完整性、合法性、可靠性、可操作性或可用性不承担任何责任。</br>
    本站对链接到的其他页面中的任何信息或材料的刪除、存储失败、错误提供或未及时提供不承担任何责任。</br>
    本站对因通过本站访问网上的任何信息或材料而导致的任何伤害不承担任何责任。</br>
    本站所包含的网站资源信息内的所有内容并不反映亦不代表任何本站之意见本站提供的所有内容仅供学习、分享与交流；本站不保证内容的正确性，通过使用本站内容随之而来的风险与本站无关。</br>
    当使用本站时，代表你已接受本站的免费声明和隐私原则等条款。</br>
    本服务条款的解释权与修改权属于本站</font></p></br>'
  webmaster:
    head: 关于站长
    name: 慕雪
    url: https://musnow.top/?utm_source=web-stack
    img: /images/myfavicon2x.png
    description: 爱折腾的代码初学者
    html: ''

since: 2023

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
